### ISSUE TITLE
message hash changes

### ISSUE THREAD

**Issue by djrtwo** [ethereum/cbc-casper#101]
# Issue
Message currently requires random "salt" to distinguish between messages of same sender/sequence number, but we should be clearer about what we are doing.

The reason the salt was added -- when we add in equivocations and hash referenced justifications, we need be able to distinguish the equivocating messages from each other. 

# Proposed Implementation
- add attribute to message -- `header`
- seed `header` with just a random number for now
- modify `__hash__` to return `sha(self.header)`
- In future, can set header to actual message header if we want.

**Comment by naterush** [comment]
I'm not sure that adding some random salt is much of a hack -- to some degree, it simulates the blockhash of blocks in the real world (which are some random string generated by the `sha3(rlp(blockHeader))`). 

In fact, I'd be more comfortable doing away with `__hash__` referencing  `sequence_number` and `sender` entirely, and just reference this salt. Same for including the hashes of the justification. This way, we don't have to worry about there being any possibility of set inclusion checks (or anything else like this) is getting screwed up because of some invalid message and/or equivocation. 

For example, you can imagine that if we had `__hash__` include the `sequence_number`, `sender`, and the hashes of the justification of the message, a validator could create two messages, where one is invalid and they are an equivocation, where these messages have different estimates but the same justification, where they would be seen as the same message,

**Comment by naterush** [comment]
I think this might relate to a bigger discussion: it might make sense to separate the `block_hash` from the `__hash__`. The only reason I say this is that when we use `__hash__` as the `block_hash`, things get very confusing when we start passing messages around with references to other messages by their hashes. 

For example, we need to eventually include just `block_hashes` in the justification of a message (rather than the messages themselves). I found this very confusing and not at all intuitive when trying to do this using `__hash__` as the `block_hash` (because now checking set inclusion seems really weird, etc). 

Not sure this totally makes sense, but let me know what you think.

**Comment by djrtwo** [comment]
I hear you. I am wanting to more so simulate `sha3(rlp(blockHeader))`, where the blockheader includes `[sender, estimate, justifications]`. I forgot to include the estimate in my proposal above. Barring transactions (and some merkle root), I think those three things are what we need to ensure a uniq hash. We should add something like the justifications need to be sorted to prevent worrying about set inclusion. Or we could put them in a merkle tree and just include the root.

Not sure what you're getting at between `__hash__` and `blockhash`. Let's chat about all this briefly after the casper standup today.
