### ISSUE TITLE
DOS Prevention + Performance

### ISSUE THREAD

**Issue by naterush** [ethereum/cbc-casper#132]
# Issue
- What's wrong?
- How are things currently?
- How should things be?

# Proposed Implementation
Fill this out as best you can, and we'll start the discussion to flesh it out.

**Comment by vladzamfir** [comment]
Skipblocks would make checking agreement between blocks more efficient (sublinear instead of linear)

Right now we follow prevblock pointers from the higher-sequence-number-block until we hit the other block (or not).

If we had pointers to every 2^n blocks for blocks with sequence h, such that h % 2^n == 0, then we could do it in sublinear time.

**Comment by naterush** [comment]
Opening new issue for skip blocks, and closing this undefined one.
