### ISSUE TITLE
Use pyEVM for peering

### ISSUE THREAD

**Issue by djrtwo** [ethereum/cbc-casper#135]
# Issue
pyEVM's client/networking structure might be useful in implementing peering in this repo. Might be useful for just the EVM consensus or maybe all of them.

# Proposed Implementation
Investigate what this would actually look like and propose implementation here.

**Comment by naterush** [comment]
I'm gonna close this for now. I think the general consensus is that this repo is going to stay ~researchy~ rather than necessarily being a production implementation - and as such, any peering would be done in something for a) a specific testnet, or b) a general client implementation of CBC Casper :D
